import React, { useContext, useEffect } from "react";
import { DoctorContext } from "../../context/DoctorContext";
import { AppContext } from "../../context/AppContext";
import jsPDF from "jspdf";
import { assets } from "../../assets/assets";

const DoctorAppointments = () => {
  const {
    dToken,
    appointments,
    getAppointments,
    cancelAppointment,
    completeAppointment,
  } = useContext(DoctorContext);
  const { slotDateFormat, calculateAge, currency } = useContext(AppContext);

  useEffect(() => {
    if (dToken) {
      getAppointments();
    }
  }, [dToken]);

  const generateAppointmentReport = () => {
    const doc = new jsPDF();
    const primaryColor = "#580700"; // Customize the color for the report

    // Convert the logo to a data URL
    const logo = new Image();
    logo.src = assets.doctor_icon;
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    canvas.width = logo.width;
    canvas.height = logo.height;
    ctx.drawImage(logo, 0, 0);
    const logoDataUrl = canvas.toDataURL("image/png");

    // Add logo
    doc.addImage(logoDataUrl, "PNG", 14, 10, 25, 25);

    // Add horizontal line
    doc.setDrawColor(primaryColor);
    doc.line(14, 45, 196, 45);

    // Report title
    doc.setFontSize(18);
    doc.setTextColor(primaryColor);
    doc.text("Appointment Report", 14, 60);

    // Table header
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.setFillColor(primaryColor);
    doc.rect(14, 70, 182, 10, "F");
    doc.text("Date", 16, 77);
    doc.text("Patient", 50, 77);
    doc.text("Age", 100, 77);
    doc.text("Payment", 120, 77);
    doc.text("Amount", 150, 77);

    let yPos = 85;
    let totalRevenue = 0;

    appointments.forEach((item, index) => {
      if (!item.cancelled) {
        if (yPos > 280) {
          doc.addPage();
          yPos = 20;

          // Add header to new page
          doc.setFillColor(primaryColor);
          doc.rect(14, yPos, 182, 10, "F");
          doc.setTextColor(255, 255, 255);
          doc.text("Date", 16, yPos + 7);
          doc.text("Patient", 50, yPos + 7);
          doc.text("Age", 100, yPos + 7);
          doc.text("Payment", 120, yPos + 7);
          doc.text("Amount", 150, yPos + 7);
          yPos += 15;
        }

        doc.setTextColor(0);
        doc.text(slotDateFormat(item.slotDate), 16, yPos);
        doc.text(item.userData.name.substring(0, 20), 50, yPos);
        doc.text(`${calculateAge(item.userData.dob)}`, 100, yPos);
        doc.text(item.payment ? "Online" : "Cash", 120, yPos);
        doc.text(`${currency}${item.amount}`, 150, yPos);

        totalRevenue += parseFloat(item.amount);
        yPos += 10;
      }
    });

    yPos += 10;
    doc.setFontSize(14);
    doc.setTextColor(primaryColor);
    doc.text(`Total Revenue: ${currency}${totalRevenue.toFixed(2)}`, 14, yPos);

    // Add footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Page ${i} of ${pageCount}`, 196, 285, null, null, "right");
      doc.text("Generated by MedicareX", 14, 285);
    }

    return doc;
  };

  const downloadAppointmentReport = () => {
    const doc = generateAppointmentReport();
    doc.save("MedicareX_Appointment_Report.pdf");
  };

  return (
    <div className="w-full max-w-6xl m-5 ">
      <div className="flex justify-between items-center mb-3">
        <p className="text-lg font-medium">All Appointments</p>
        <button
          onClick={downloadAppointmentReport}
          className="bg-[#ac3429] hover:bg-[#580700] text-white font-bold py-2 px-4 rounded"
        >
          Download Appointment Report
        </button>
      </div>

      <div className="bg-white border rounded text-sm max-h-[80vh] overflow-y-scroll">
        <div className="hidden sm:grid grid-cols-[0.5fr_2fr_1fr_1fr_3fr_1fr_1fr] grid-flow-col py-3 px-6 border-b">
          <p>#</p>
          <p>Patient</p>
          <p>Payment</p>
          <p>Age</p>
          <p>Date & Time</p>
          <p>Fees</p>
          <p>Action</p>
        </div>
        {appointments.map((item, index) => (
          <div
            className="flex flex-wrap justify-between max-sm:gap-2 sm:grid sm:grid-cols-[0.5fr_2fr_1fr_1fr_3fr_1fr_1fr] items-center text-gray-500 py-3 px-6 border-b hover:bg-gray-50"
            key={index}
          >
            <p className="max-sm:hidden">{index + 1}</p>
            <div className="flex items-center gap-2">
              <img
                src={item.userData.image}
                className="w-8 rounded-full"
                alt=""
              />{" "}
              <p>{item.userData.name}</p>
            </div>
            <div>
              <p className="text-xs inline border border-primary px-2 rounded-full">
                {item.payment ? "Online" : "CASH"}
              </p>
            </div>
            <p className="max-sm:hidden">{calculateAge(item.userData.dob)}</p>
            <p>
              {slotDateFormat(item.slotDate)}, {item.slotTime}
            </p>
            <p>
              {currency}
              {item.amount}
            </p>
            {item.cancelled ? (
              <p className="text-red-400 text-xs font-medium">Cancelled</p>
            ) : item.isCompleted ? (
              <p className="text-green-500 text-xs font-medium">Completed</p>
            ) : (
              <div className="flex">
                <img
                  onClick={() => cancelAppointment(item._id)}
                  className="w-10 cursor-pointer"
                  src={assets.cancel_icon}
                  alt=""
                />
                <img
                  onClick={() => completeAppointment(item._id)}
                  className="w-10 cursor-pointer"
                  src={assets.tick_icon}
                  alt=""
                />
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default DoctorAppointments;
